import type { Award, BlogPost, Publication, ResearchItem } from "./types";

const id = (n: number) => `seed-${n}`;

export const seedResearch: ResearchItem[] = [
  {
    id: id(1),
    slug: "human-brain-development",
    title: "Human Brain Development",
    card_title: "Human Brain Development",
    card_summary: "Molecular logic of cortical development and cellular diversity.",
    subtitle: "Decoding the molecular logic of human cortical development",
    question: "How does the human brain generate its extraordinary cellular diversity?",
    body: "This theme investigates the molecular and transcriptional programs that regulate neural progenitor proliferation, cell-fate specification, neuronal differentiation and cortical organization during human development. It frames how the human cortex becomes unique, and how those programs can fail.",
    extra_line: "",
    image_url: "/images/lab/theme-development.jpg",
    image_caption: "Cortical neurons · Fluorescence field",
    accent: "cyan",
    sort_order: 1,
    published: true,
  },
  {
    id: id(2),
    slug: "rna-biology",
    title: "RNA Biology & Isoform Diversity",
    card_title: "RNA Biology & Isoforms",
    card_summary: "How alternative splicing shapes identity and disease risk.",
    subtitle: "Beyond genes: the complexity of RNA isoforms",
    question: "How does RNA processing create molecular diversity that shapes fate and disease?",
    body: "The genome provides the blueprint; RNA processing creates enormous molecular diversity. A major focus is alternative splicing and isoform diversity during human brain development and in neurological disease, and how changes in RNA processing alter cellular identity, trajectories and susceptibility.",
    extra_line: "",
    image_url: "/images/lab/theme-rna.jpg",
    image_caption: "RNA splicing · Isoform diversity",
    accent: "magenta",
    sort_order: 2,
    published: true,
  },
  {
    id: id(3),
    slug: "organoids",
    title: "Human Brain Organoids & Assembloids",
    card_title: "Organoids & Assembloids",
    card_summary: "Human brain models: cortical, interneuron and vascular systems.",
    subtitle: "Building the human brain in a dish",
    question: "How can human-relevant models capture interactions animal systems miss?",
    body: "Patient-derived and human iPSC-derived cortical, interneuron and vascular organoids, and increasingly complex assembloids, model development and disease in a genetically authentic human context, enabling mechanism studies and therapeutic testing.",
    extra_line: "",
    image_url: "/images/lab/theme-organoids.jpg",
    image_caption: "Human cerebral organoids · Culture systems",
    accent: "amber",
    sort_order: 3,
    published: true,
  },
  {
    id: id(4),
    slug: "single-cell",
    title: "Single-Cell & Spatial Neuroscience",
    card_title: "Single-Cell & Spatial",
    card_summary: "Mapping development and disease at single-cell resolution.",
    subtitle: "Mapping the human brain at single-cell resolution",
    question: "How do we connect genes to circuits across development and disease?",
    body: "Single-cell, single-nucleus and spatial technologies map cellular and molecular diversity across stages and disease states, connecting:",
    extra_line: "Genes → RNA → Cell States → Cellular Interactions → Neural Circuits → Disease Phenotypes",
    image_url: "/images/lab/theme-spatial.jpg",
    image_caption: "Cellular architecture · Multicolor fluorescence",
    accent: "cyan",
    sort_order: 4,
    published: true,
  },
  {
    id: id(5),
    slug: "disease",
    title: "Neurodevelopmental & Psychiatric Disorders",
    card_title: "Neurodevelopmental Disease",
    card_summary: "Autism, Down syndrome, bipolar disorder and schizophrenia.",
    subtitle: "From developmental biology to disease mechanisms",
    question: "How do early developmental disruptions become clinical disease?",
    body: "Many neurological and psychiatric disorders have roots in early development. This work investigates Autism Spectrum Disorder, Down syndrome, bipolar disorder and schizophrenia, combining patient-derived iPSCs with multi-organoid models and multimodal profiling to explain why patients with the same diagnosis can show very different biology.",
    extra_line: "",
    image_url: "/images/lab/theme-disease.jpg",
    image_caption: "Spiny neuron · Confocal microscopy",
    accent: "magenta",
    sort_order: 5,
    published: true,
  },
  {
    id: id(6),
    slug: "precision-psychiatry",
    title: "Precision Psychiatry",
    card_title: "Precision Psychiatry",
    card_summary: "Biological subtypes and mechanism-based therapies.",
    subtitle: "From patient heterogeneity to precision medicine",
    question: "Can we define biological subtypes that guide mechanism-based therapy?",
    body: "Two patients with the same diagnosis may have different underlying mechanisms. The long-term vision combines clinical phenotyping, patient-derived iPSCs, organoids, single-cell genomics, functional phenotyping and computation to identify biological subtypes and develop mechanism-based strategies.",
    extra_line: "",
    image_url: "/images/lab/theme-brain.jpg",
    image_caption: "Human brain · Systems-level insight",
    accent: "amber",
    sort_order: 6,
    published: true,
  },
];

export const seedPublications: Publication[] = [
  { id: id(101), authors: "Palacios Moriano J, Mukhtar T, et al.", title: "A multimodal atlas of Broca's area in the developing human brain.", venue: "Cell", year_label: "2026", note: "In revision", doi_url: null, image_url: "/images/lab/theme-brain.jpg", category: "first", featured: false, sort_order: 1, published: true },
  { id: id(102), authors: "Mukhtar T, Siebert CV, Wang Y, Pebworth MP, White ML, Li J, Kriegstein AR.", title: "α7 nicotinic acetylcholine receptors regulate radial glia fate in the developing human cortex.", venue: "Nature Communications", year_label: "2025", note: "", doi_url: "https://doi.org/10.1038/s41467-025-61167-5", image_url: "/images/lab/pubs/pub-radial-glia.jpg", category: "first", featured: true, sort_order: 2, published: true },
  { id: id(103), authors: "Mukhtar T, Taylor V.", title: "Dynamic transcriptional programs define distinct mammalian cortical lineages.", venue: "Neural Regeneration Research", year_label: "2024", note: "", doi_url: "https://doi.org/10.4103/1673-5374.377589", image_url: "/images/lab/theme-rna.jpg", category: "first", featured: false, sort_order: 3, published: true },
  { id: id(104), authors: "Mukhtar T, Taylor V.", title: "Temporal and sequential transcriptional dynamics define lineage shifts in corticogenesis.", venue: "The EMBO Journal", year_label: "2022", note: "", doi_url: null, image_url: "/images/lab/pubs/pub-radial-dev.jpg", category: "first", featured: false, sort_order: 4, published: true },
  { id: id(105), authors: "Andrews M, Mukhtar T, et al.", title: "Tropism of SARS-CoV-2 for Developing Human Cortical Astrocytes.", venue: "PNAS", year_label: "2022", note: "", doi_url: "https://doi.org/10.1073/pnas.2122236119", image_url: "/images/lab/pubs/pub-astrocyte.jpg", category: "first", featured: false, sort_order: 5, published: true },
  { id: id(106), authors: "Mukhtar T, et al.", title: "Tead transcription factors differentially regulate cortical development.", venue: "Scientific Reports", year_label: "2020", note: "", doi_url: null, image_url: "/images/lab/pubs/pub-tf-dna.jpg", category: "first", featured: false, sort_order: 6, published: true },
  { id: id(107), authors: "Mukhtar T, Taylor V.", title: "Untangling Cortical Complexity During Development.", venue: "Journal of Experimental Neuroscience", year_label: "2018", note: "", doi_url: null, image_url: "/images/lab/pubs/pub-pc12.jpg", category: "first", featured: false, sort_order: 7, published: true },
  { id: id(201), authors: "Wu T, Jiang L, Mukhtar T, et al.", title: "Single Cell Proteomics in the Developing Human Brain.", venue: "Nature Biotechnology", year_label: "2026", note: "", doi_url: "https://doi.org/10.1038/s41587-025-02980-7", image_url: "/images/lab/pubs/pub-scrna.jpg", category: "collaborative", featured: false, sort_order: 1, published: true },
  { id: id(202), authors: "Wang JC, Sanchez D, et al., including Mukhtar T.", title: "Spatially resolved molecular cartography reveals specialized cell ensembles in the human brain vasculature.", venue: "Cell", year_label: "2026", note: "", doi_url: null, image_url: "/images/lab/pubs/pub-organoid2.jpg", category: "collaborative", featured: false, sort_order: 2, published: true },
  { id: id(203), authors: "Wang L, Moriano JA, Chen S, et al., including Mukhtar T.", title: "Molecular and cellular dynamics of the developing human neocortex.", venue: "Nature", year_label: "2025", note: "", doi_url: "https://doi.org/10.1038/s41586-024-08351-7", image_url: "/images/lab/pubs/pub-neocortex.jpg", category: "collaborative", featured: false, sort_order: 3, published: true },
  { id: id(204), authors: "Mostajo-Radji MA, Leon WRM, et al., including Mukhtar T.", title: "Fate plasticity of interneuron specification.", venue: "iScience", year_label: "2025", note: "", doi_url: "https://doi.org/10.1016/j.isci.2025.112295", image_url: "/images/lab/pubs/pub-interneuron-glia.jpg", category: "collaborative", featured: false, sort_order: 4, published: true },
  { id: id(205), authors: "Ifflander N, Rolando C, Balta EA, Mukhtar T, et al.", title: "Safb1 regulates cell fate determination in the adult brain by enhancing mRNA cleavage.", venue: "eLife", year_label: "2024", note: "", doi_url: null, image_url: "/images/lab/pubs/pub-genome-tf.jpg", category: "collaborative", featured: false, sort_order: 5, published: true },
  { id: id(206), authors: "Andrews MG, Siebert C, Wang L, et al., including Mukhtar T.", title: "LIF signaling regulates outer radial glia to interneuron fate during human cortical development.", venue: "Cell Stem Cell", year_label: "2023", note: "", doi_url: "https://doi.org/10.1016/j.stem.2023.08.009", image_url: "/images/lab/theme-organoids.jpg", category: "collaborative", featured: false, sort_order: 6, published: true },
  { id: id(207), authors: "Crawford E, … Mukhtar T, … Derisi J.", title: "Rapid deployment of SARS-CoV-2 testing: the CLIAHUB.", venue: "PLoS Pathogens", year_label: "2020", note: "", doi_url: null, image_url: "/images/lab/pubs/pub-sars.jpg", category: "collaborative", featured: false, sort_order: 7, published: true },
  { id: id(208), authors: "Zhang C, Tu HL, Jia G, Mukhtar T, et al.", title: "Ultra-Multiplexed Analysis of Single Cell Dynamics Reveals Logic Rules in Differentiation.", venue: "Science Advances", year_label: "2019", note: "", doi_url: null, image_url: "/images/lab/theme-spatial.jpg", category: "collaborative", featured: false, sort_order: 8, published: true },
  { id: id(301), authors: "Robert Beattie, Mukhtar T, Verdon Taylor et al.", title: "Fundamentals of neurogenesis and neural stem cell development.", venue: "Neural Surface Antigens. Elsevier", year_label: "2014", note: "Book chapter", doi_url: null, image_url: "/images/lab/theme-development.jpg", category: "chapter", featured: false, sort_order: 1, published: true },
];

export const seedAwards: Award[] = [
  { id: id(401), year_label: "2026", title: "Prime Minister's Early Career Research Grant (PMECRG)", detail: "ANRF, Government of India · Principal Investigator", category: "fellowship", sort_order: 1, published: true },
  { id: id(402), year_label: "2025", title: "Ramanujan Fellowship", detail: "Department of Science & Technology, Government of India", category: "fellowship", sort_order: 2, published: true },
  { id: id(403), year_label: "2023", title: "Independent Postdoctoral Research Award", detail: "Institute of Regenerative Medicine, UCSF · PI", category: "fellowship", sort_order: 3, published: true },
  { id: id(404), year_label: "2019–2021", title: "SNSF Early Postdoc Mobility Fellowship", detail: "Swiss National Science Foundation", category: "fellowship", sort_order: 4, published: true },
  { id: id(405), year_label: "2013–2017", title: "ESKAS Swiss Government Excellence Scholarship", detail: "Swiss Confederation · PhD Scholar", category: "fellowship", sort_order: 5, published: true },
  { id: id(406), year_label: "2010–2011", title: "HSBC-Chevening Scholarship", detail: "Foreign & Commonwealth Office, UK", category: "fellowship", sort_order: 6, published: true },
  { id: id(407), year_label: "2009", title: "Goldman Sachs Global Leadership Award", detail: "Goldman Sachs", category: "fellowship", sort_order: 7, published: true },
  { id: id(408), year_label: "2020", title: "Dean's Commendation for Exceptional Volunteering", detail: "UCSF", category: "fellowship", sort_order: 8, published: true },
  { id: id(409), year_label: "2007–2010", title: "Principal's Prize: Maria Philip Award", detail: "Best All-Rounder Student, Mount Carmel College", category: "fellowship", sort_order: 9, published: true },
  { id: id(501), year_label: "2020", title: "TEDx Speaker", detail: "2020", category: "recognition", sort_order: 1, published: true },
  { id: id(502), year_label: "", title: "Global Perspectives Programme", detail: "Swiss Embassy, Washington D.C.", category: "recognition", sort_order: 2, published: true },
  { id: id(503), year_label: "2026 – Present", title: "Founding Director, GENE-India Foundation", detail: "2026 – Present", category: "recognition", sort_order: 3, published: true },
  { id: id(504), year_label: "", title: "Core Team Leader, Kashmir Care Foundation", detail: "", category: "recognition", sort_order: 4, published: true },
  { id: id(505), year_label: "", title: "Advisory Council Member, Kashmir Care Foundation", detail: "", category: "recognition", sort_order: 5, published: true },
  { id: id(506), year_label: "", title: "Lifetime Member, Indian Academy of Neurosciences", detail: "", category: "recognition", sort_order: 6, published: true },
  { id: id(507), year_label: "", title: "Member, ISSCR", detail: "International Society for Stem Cell Research", category: "recognition", sort_order: 7, published: true },
  { id: id(508), year_label: "", title: "Member, Society for Neuroscience (SfN)", detail: "", category: "recognition", sort_order: 8, published: true },
];

export const seedBlogs: BlogPost[] = [];
