import type { Award, GalleryItem, Publication, ResearchItem, Resource } from "./types";

const id = (n: number) => `seed-${n}`;

export const seedResearch: ResearchItem[] = [
  {
    id: id(1),
    slug: "human-brain-development",
    title: "Human Brain Development",
    card_title: "Human Brain Development",
    card_summary: "Molecular logic of cortical development and cellular diversity.",
    subtitle: "Decoding the molecular logic of human cortical development",
    question: "How does the human brain generate its extraordinary cellular diversity?",
    body: "This theme investigates the molecular and transcriptional programs that regulate neural progenitor proliferation, cell-fate specification, neuronal differentiation and cortical organization during human development. It frames how the human cortex becomes unique, and how those programs can fail.",
    extra_line: "",
    image_url: "/images/lab/picture-9.jpg",
    image_caption: "Cortical neurons and radial progenitors",
    accent: "cyan",
    sort_order: 1,
    published: true,
  },
  {
    id: id(2),
    slug: "rna-biology",
    title: "RNA Biology & Isoform Diversity",
    card_title: "RNA Biology & Isoforms",
    card_summary: "How alternative splicing shapes identity and disease risk.",
    subtitle: "Beyond genes: the complexity of RNA isoforms",
    question: "How does RNA processing create molecular diversity that shapes fate and disease?",
    body: "The genome provides the blueprint; RNA processing creates enormous molecular diversity. A major focus is alternative splicing and isoform diversity during human brain development and in neurological disease, and how changes in RNA processing alter cellular identity, trajectories and susceptibility.",
    extra_line: "",
    image_url: "/images/lab/primary-cells.jpg",
    image_caption: "Primary cells in culture",
    accent: "magenta",
    sort_order: 2,
    published: true,
  },
  {
    id: id(3),
    slug: "organoids",
    title: "Human Brain Organoids & Assembloids",
    card_title: "Organoids & Assembloids",
    card_summary: "Human brain models: cortical, interneuron and vascular systems.",
    subtitle: "Building the human brain in a dish",
    question: "How can human-relevant models capture interactions animal systems miss?",
    body: "Patient-derived and human iPSC-derived cortical, interneuron and vascular organoids, and increasingly complex assembloids, model development and disease in a genetically authentic human context, enabling mechanism studies and therapeutic testing.",
    extra_line: "",
    image_url: "/images/lab/organoid-week-10.jpg",
    image_caption: "Week 10 cortical organoid",
    accent: "amber",
    sort_order: 3,
    published: true,
  },
  {
    id: id(4),
    slug: "single-cell",
    title: "Single-Cell & Spatial Neuroscience",
    card_title: "Single-Cell & Spatial",
    card_summary: "Mapping development and disease at single-cell resolution.",
    subtitle: "Mapping the human brain at single-cell resolution",
    question: "How do we connect genes to circuits across development and disease?",
    body: "Single-cell, single-nucleus and spatial technologies map cellular and molecular diversity across stages and disease states, connecting:",
    extra_line: "Genes → RNA → Cell States → Cellular Interactions → Neural Circuits → Disease Phenotypes",
    image_url: "/images/lab/picture-6.jpg",
    image_caption: "Fluorescent cortical tissue",
    accent: "cyan",
    sort_order: 4,
    published: true,
  },
  {
    id: id(5),
    slug: "disease",
    title: "Neurodevelopmental & Psychiatric Disorders",
    card_title: "Neurodevelopmental Disease",
    card_summary: "Autism, Down syndrome, bipolar disorder and schizophrenia.",
    subtitle: "From developmental biology to disease mechanisms",
    question: "How do early developmental disruptions become clinical disease?",
    body: "Many neurological and psychiatric disorders have roots in early development. This work investigates Autism Spectrum Disorder, Down syndrome, bipolar disorder and schizophrenia, combining patient-derived iPSCs with multi-organoid models and multimodal profiling to explain why patients with the same diagnosis can show very different biology.",
    extra_line: "",
    image_url: "/images/lab/picture-10.jpg",
    image_caption: "Astrocytes",
    accent: "magenta",
    sort_order: 5,
    published: true,
  },
  {
    id: id(6),
    slug: "precision-psychiatry",
    title: "Precision Psychiatry",
    card_title: "Precision Psychiatry",
    card_summary: "Biological subtypes and mechanism-based therapies.",
    subtitle: "From patient heterogeneity to precision medicine",
    question: "Can we define biological subtypes that guide mechanism-based therapy?",
    body: "Two patients with the same diagnosis may have different underlying mechanisms. The long-term vision combines clinical phenotyping, patient-derived iPSCs, organoids, single-cell genomics, functional phenotyping and computation to identify biological subtypes and develop mechanism-based strategies.",
    extra_line: "",
    image_url: "/images/lab/fused-organoids.jpg",
    image_caption: "Fused organoids",
    accent: "amber",
    sort_order: 6,
    published: true,
  },
];

export const seedPublications: Publication[] = [
  { id: id(101), authors: "Palacios Moriano J, Mukhtar T, et al.", title: "A multimodal atlas of Broca's area in the developing human brain.", venue: "Cell", year_label: "2026", note: "In revision", doi_url: "https://doi.org/10.64898/2026.07.22.739934", image_url: "/images/lab/picture-8.jpg", category: "first", featured: false, sort_order: 1, published: true },
  { id: id(102), authors: "Mukhtar T, Siebert CV, Wang Y, Pebworth MP, White ML, Li J, Kriegstein AR.", title: "α7 nicotinic acetylcholine receptors regulate radial glia fate in the developing human cortex.", venue: "Nature Communications", year_label: "2025", note: "", doi_url: "https://doi.org/10.1038/s41467-025-61167-5", image_url: "/images/lab/picture-9.jpg", category: "first", featured: true, sort_order: 2, published: true },
  { id: id(103), authors: "Mukhtar T, Taylor V.", title: "Dynamic transcriptional programs define distinct mammalian cortical lineages.", venue: "Neural Regeneration Research", year_label: "2024", note: "", doi_url: "https://doi.org/10.4103/1673-5374.377589", image_url: "/images/lab/primary-cells.jpg", category: "first", featured: false, sort_order: 3, published: true },
  { id: id(104), authors: "Mukhtar T, Taylor V.", title: "Temporal and sequential transcriptional dynamics define lineage shifts in corticogenesis.", venue: "The EMBO Journal", year_label: "2022", note: "", doi_url: "https://doi.org/10.15252/embj.2022111132", image_url: "/images/lab/organoid-week-5.jpg", category: "first", featured: false, sort_order: 4, published: true },
  { id: id(105), authors: "Andrews M, Mukhtar T, et al.", title: "Tropism of SARS-CoV-2 for Developing Human Cortical Astrocytes.", venue: "PNAS", year_label: "2022", note: "", doi_url: "https://doi.org/10.1073/pnas.2122236119", image_url: "/images/lab/picture-10.jpg", category: "first", featured: false, sort_order: 5, published: true },
  { id: id(106), authors: "Mukhtar T, et al.", title: "Tead transcription factors differentially regulate cortical development.", venue: "Scientific Reports", year_label: "2020", note: "", doi_url: "https://doi.org/10.1038/s41598-020-61490-5", image_url: "/images/lab/picture-6.jpg", category: "first", featured: false, sort_order: 6, published: true },
  { id: id(107), authors: "Mukhtar T, Taylor V.", title: "Untangling Cortical Complexity During Development.", venue: "Journal of Experimental Neuroscience", year_label: "2018", note: "", doi_url: "https://doi.org/10.1177/1179069518759332", image_url: "/images/lab/primary-tissue.jpg", category: "first", featured: false, sort_order: 7, published: true },
  { id: id(201), authors: "Wu T, Jiang L, Mukhtar T, et al.", title: "Single Cell Proteomics in the Developing Human Brain.", venue: "Nature Biotechnology", year_label: "2026", note: "", doi_url: "https://doi.org/10.1038/s41587-025-02980-7", image_url: "/images/lab/picture-7.jpg", category: "collaborative", featured: false, sort_order: 1, published: true },
  { id: id(202), authors: "Wang JC, Sanchez D, et al., including Mukhtar T.", title: "Spatially resolved molecular cartography reveals specialized cell ensembles in the human brain vasculature.", venue: "Cell", year_label: "2026", note: "", doi_url: "https://doi.org/10.1016/j.cell.2026.07.007", image_url: "/images/lab/sars-primary-tissue.jpg", category: "collaborative", featured: false, sort_order: 2, published: true },
  { id: id(203), authors: "Wang L, Moriano JA, Chen S, et al., including Mukhtar T.", title: "Molecular and cellular dynamics of the developing human neocortex.", venue: "Nature", year_label: "2025", note: "", doi_url: "https://doi.org/10.1038/s41586-024-08351-7", image_url: "/images/lab/organoid-week-10.jpg", category: "collaborative", featured: false, sort_order: 3, published: true },
  { id: id(204), authors: "Mostajo-Radji MA, Leon WRM, et al., including Mukhtar T.", title: "Fate plasticity of interneuron specification.", venue: "iScience", year_label: "2025", note: "", doi_url: "https://doi.org/10.1016/j.isci.2025.112295", image_url: "/images/lab/fused-organoids.jpg", category: "collaborative", featured: false, sort_order: 4, published: true },
  { id: id(205), authors: "Ifflander N, Rolando C, Balta EA, Mukhtar T, et al.", title: "Safb1 regulates cell fate determination in the adult brain by enhancing mRNA cleavage.", venue: "eLife", year_label: "2024", note: "", doi_url: "https://doi.org/10.7554/eLife.74940", image_url: "/images/lab/astrocytes.jpg", category: "collaborative", featured: false, sort_order: 5, published: true },
  { id: id(206), authors: "Andrews MG, Siebert C, Wang L, et al., including Mukhtar T.", title: "LIF signaling regulates outer radial glia to interneuron fate during human cortical development.", venue: "Cell Stem Cell", year_label: "2023", note: "", doi_url: "https://doi.org/10.1016/j.stem.2023.08.009", image_url: "/images/lab/picture-5.jpg", category: "collaborative", featured: false, sort_order: 6, published: true },
  { id: id(207), authors: "Crawford E, … Mukhtar T, … Derisi J.", title: "Rapid deployment of SARS-CoV-2 testing: the CLIAHUB.", venue: "PLoS Pathogens", year_label: "2020", note: "", doi_url: null, image_url: "/images/lab/gw17-neurons.jpg", category: "collaborative", featured: false, sort_order: 7, published: true },
  { id: id(208), authors: "Zhang C, Tu HL, Jia G, Mukhtar T, et al.", title: "Ultra-Multiplexed Analysis of Single Cell Dynamics Reveals Logic Rules in Differentiation.", venue: "Science Advances", year_label: "2019", note: "", doi_url: "https://doi.org/10.1126/sciadv.aav7959", image_url: "/images/lab/organoid-week-5.jpg", category: "collaborative", featured: false, sort_order: 8, published: true },
  { id: id(209), authors: "Arren Ramsey, et al., including Mukhtar T.", title: "TGF-β signaling promotes astroglial activation and TDP-43 proteinopathy in organoid models of frontotemporal lobar degeneration.", venue: "Journal of Clinical Investigation", year_label: "2026", note: "", doi_url: "https://doi.org/10.1172/JCI190035", image_url: "/images/lab/picture-7.jpg", category: "collaborative", featured: false, sort_order: 9, published: true },
  { id: id(301), authors: "Robert Beattie, Mukhtar T, Verdon Taylor et al.", title: "Fundamentals of neurogenesis and neural stem cell development.", venue: "Neural Surface Antigens. Elsevier", year_label: "2014", note: "Book chapter", doi_url: null, image_url: "/images/lab/primary-tissue.jpg", category: "chapter", featured: false, sort_order: 1, published: true },
];

export const seedAwards: Award[] = [
  { id: id(401), year_label: "2026", title: "Prime Minister's Early Career Research Grant (PMECRG)", detail: "ANRF, Government of India · Principal Investigator", category: "fellowship", sort_order: 1, published: true },
  { id: id(402), year_label: "2025", title: "Ramanujan Fellowship", detail: "Department of Science & Technology, Government of India", category: "fellowship", sort_order: 2, published: true },
  { id: id(403), year_label: "2023", title: "Independent Postdoctoral Research Award", detail: "Institute of Regenerative Medicine, UCSF · PI", category: "fellowship", sort_order: 3, published: true },
  { id: id(404), year_label: "2019–2021", title: "SNSF Early Postdoc Mobility Fellowship", detail: "Swiss National Science Foundation", category: "fellowship", sort_order: 4, published: true },
  { id: id(405), year_label: "2013–2017", title: "ESKAS Swiss Government Excellence Scholarship", detail: "Swiss Confederation · PhD Scholar", category: "fellowship", sort_order: 5, published: true },
  { id: id(406), year_label: "2010–2011", title: "HSBC-Chevening Scholarship", detail: "Foreign and Commonwealth Office / British High Commission, UK · Chevening Scholar", category: "fellowship", sort_order: 6, published: true },
  { id: id(407), year_label: "2009", title: "Goldman Sachs Global Leadership Award", detail: "Goldman Sachs", category: "fellowship", sort_order: 7, published: true },
  { id: id(408), year_label: "2020", title: "Dean's Commendation for Exceptional Volunteering & Community Service", detail: "UCSF", category: "fellowship", sort_order: 8, published: true },
  { id: id(409), year_label: "2007–2010", title: "Principal's Prize: Maria Philip Award", detail: "Best All-Rounder Student, Mount Carmel College", category: "fellowship", sort_order: 9, published: true },
  { id: id(501), year_label: "2020", title: "TEDx Speaker", detail: "2020", category: "recognition", sort_order: 1, published: true },
  { id: id(502), year_label: "", title: "Global Perspectives Programme", detail: "Swiss Embassy, Washington D.C.", category: "recognition", sort_order: 2, published: true },
  { id: id(503), year_label: "2026 – Present", title: "Founding Director, GENE-India Foundation", detail: "2026 – Present", category: "recognition", sort_order: 3, published: true },
  { id: id(504), year_label: "", title: "Core Team Leader, Kashmir Care Foundation", detail: "", category: "recognition", sort_order: 4, published: true },
  { id: id(505), year_label: "", title: "Advisory Council Member, Kashmir Care Foundation", detail: "", category: "recognition", sort_order: 5, published: true },
  { id: id(506), year_label: "", title: "Lifetime Member, Indian Academy of Neurosciences", detail: "", category: "recognition", sort_order: 6, published: true },
  { id: id(507), year_label: "", title: "Member, ISSCR", detail: "International Society for Stem Cell Research", category: "recognition", sort_order: 7, published: true },
  { id: id(508), year_label: "", title: "Member, Society for Neuroscience (SfN)", detail: "", category: "recognition", sort_order: 8, published: true },
];

const neurostemAbstract =
  "The cerebral cortex contains billions of neurons, and their disorganization or misspecification leads to neurodevelopmental disorders. Understanding how the plethora of projection neuron subtypes are generated by cortical neural stem cells (NSCs) is a major challenge. Here, we focused on elucidating the transcriptional landscape of murine embryonic NSCs, basal progenitors (BPs) and newborn neurons (NBNs) throughout cortical development. We uncover dynamic shifts in transcriptional space over time, and heterogeneity within each progenitor population. We identified signature hallmarks of NSC, BP and NBN clusters, and predict active transcriptional nodes and networks that contribute to neural fate specification. We find that the expression of receptors, ligands and downstream pathway components is highly dynamic over time and throughout the lineage implying differential responsiveness to signals. Thus, we provide an expansive compendium of gene expression during cortical development that will be an invaluable resource for studying neural developmental processes and neurodevelopmental disorders.";

const emboCitation =
  "Mukhtar T, Taylor V. Temporal and sequential transcriptional dynamics define lineage shifts in corticogenesis. The EMBO Journal, 2022. doi: 10.15252/embj.2022111132";

export const seedResources: Resource[] = [
  {
    id: id(601),
    title: "ISMARA · NeuroStemX",
    summary: "Interactive regulatory analysis of cortical neural stem cells, basal progenitors and newborn neurons.",
    body: neurostemAbstract,
    url: "https://ismara.unibas.ch/NeuroStemX/",
    link_label: "Open ISMARA",
    citation: emboCitation,
    sort_order: 1,
    published: true,
  },
  {
    id: id(602),
    title: "NeuroStemX · Gene expression",
    summary: "Gene expression atlas of cortical development released with the 2022 EMBO Journal paper.",
    body: neurostemAbstract,
    url: "https://neurostemx.ethz.ch/#home",
    link_label: "Open gene expression atlas",
    citation: emboCitation,
    sort_order: 2,
    published: true,
  },
  {
    id: id(603),
    title: "Kashmir Care Foundation",
    summary: "Mentorship and career support for students, researchers and professionals.",
    body: "Kashmir Care Foundation (KCF) welcomes you to join our global network of students, researchers, and professionals. We bring together experts, mentors, and learners to advance education, research, and innovation. Supported by a diverse Advisory Group and Core Team, we aim to equip students and young professionals with the knowledge, soft skills, and technologies needed to excel in their careers and drive meaningful change. Our goal is to empower individuals from all backgrounds and locations, inspiring them to realize their full potential and become leaders in their fields.",
    url: "https://kashmircarefoundation.org/",
    link_label: "Visit Kashmir Care Foundation",
    citation: "",
    sort_order: 3,
    published: true,
  },
  {
    id: id(604),
    title: "GENE-India Foundation",
    summary: "Global Education and Networking for Excellence · mentorship across India.",
    body: "GENE stands for Global Education and Networking for Excellence. GENE India Foundation was founded on a simple conviction: talent is everywhere, but opportunity is not. Across India's cities, towns, and villages are students and young professionals with the drive to become tomorrow's scientists, doctors, engineers, entrepreneurs, and leaders, but not always the mentorship, exposure, or networks to get there. GENE India exists to close that gap, connecting experienced professionals from across the globe with learners at every stage of their journey. Powered entirely by volunteers who give their time, expertise, and passion, we are building a movement rooted in mentorship, equity, and lifelong learning. Write to geneindiafoundation@gmail.com.",
    url: "https://www.geneindiafoundation.org",
    link_label: "Visit GENE-India Foundation",
    citation: "",
    sort_order: 4,
    published: true,
  },
];

export const seedGallery: GalleryItem[] = [
  {
    id: id(701),
    image_url: "/images/gallery/lab-team.jpg",
    alt: "Mukhtar Lab team members together in the laboratory",
    caption: "The team · Lab members together",
    sort_order: 1,
    published: true,
  },
  {
    id: id(702),
    image_url: "/images/gallery/lab-duo.jpg",
    alt: "Two Mukhtar Lab members smiling in the laboratory, one giving a thumbs up",
    caption: "Lab mates · In the workspace",
    sort_order: 2,
    published: true,
  },
  {
    id: id(703),
    image_url: "/images/gallery/lab-work-bsc.jpg",
    alt: "Two researchers collaborating at a biosafety cabinet",
    caption: "Collaboration · Biosafety cabinet",
    sort_order: 3,
    published: true,
  },
  {
    id: id(704),
    image_url: "/images/gallery/lab-culture-work.jpg",
    alt: "Researchers performing cell culture work at a laminar flow hood",
    caption: "Cell culture · Sterile technique",
    sort_order: 4,
    published: true,
  },
  {
    id: id(705),
    image_url: "/images/gallery/lab-hood-collab.jpg",
    alt: "Two researchers collaborating at a laminar flow hood with culture dishes and pipettes",
    caption: "At the hood · Mentorship in action",
    sort_order: 5,
    published: true,
  },
  {
    id: id(706),
    image_url: "/images/gallery/lab-team-three.jpg",
    alt: "Three Mukhtar Lab members posing together in the laboratory",
    caption: "Team spirit · Together in the lab",
    sort_order: 6,
    published: true,
  },
  {
    id: id(707),
    image_url: "/images/gallery/lab-bench-work.jpg",
    alt: "Researcher working at a sterile laboratory workstation with culture dishes and pipettes",
    caption: "At the bench · Culture and preparation",
    sort_order: 7,
    published: true,
  },
  {
    id: id(708),
    image_url: "/images/gallery/lab-group-b2ac.jpg",
    alt: "Dr. Tanzila Mukhtar presenting research at a seminar with microscopy slides on screen",
    caption: "Seminar · Research presentation",
    sort_order: 8,
    published: true,
  },
  {
    id: id(709),
    image_url: "/images/gallery/lab-group-outdoor.jpg",
    alt: "Dr. Tanzila Mukhtar speaking at a podium during a scientific talk",
    caption: "Talk · At the lectern",
    sort_order: 9,
    published: true,
  },
  {
    id: id(710),
    image_url: "/images/gallery/lab-group-portrait.jpg",
    alt: "Award of Appreciation plaque presented to Dr. Tanzila Mukhtar by Govt. Degree College Sopore",
    caption: "Recognition · Award of Appreciation, GDC Sopore",
    sort_order: 10,
    published: true,
  },
  {
    id: id(711),
    image_url: "/images/gallery/lab-seminar-side.jpg",
    alt: "Students attending a seminar titled Parents as Pathfinders in a wood-paneled classroom",
    caption: "Outreach · Parents as Pathfinders",
    sort_order: 11,
    published: true,
  },
  {
    id: id(712),
    image_url: "/images/gallery/lab-seminar-front.jpg",
    alt: "Participants seated around tables during an academic seminar",
    caption: "Seminar · Discussion and engagement",
    sort_order: 12,
    published: true,
  },
  {
    id: id(713),
    image_url: "/images/gallery/lab-seminar-wide.jpg",
    alt: "Wide view of students and speakers in a classroom seminar session",
    caption: "Outreach · Classroom session",
    sort_order: 13,
    published: true,
  },
];
