-- Seed Resources and Gallery after migration-resources-gallery.sql
-- Safe to re-run: skips insert when the table already has rows.

do $$
begin
  if not exists (select 1 from public.resources limit 1) then
    insert into public.resources (title, summary, body, url, link_label, citation, sort_order, published)
    values
(
  'ISMARA · NeuroStemX',
  'Interactive regulatory analysis of cortical neural stem cells, basal progenitors and newborn neurons.',
  'The cerebral cortex contains billions of neurons, and their disorganization or misspecification leads to neurodevelopmental disorders. Understanding how the plethora of projection neuron subtypes are generated by cortical neural stem cells (NSCs) is a major challenge. Here, we focused on elucidating the transcriptional landscape of murine embryonic NSCs, basal progenitors (BPs) and newborn neurons (NBNs) throughout cortical development. We uncover dynamic shifts in transcriptional space over time, and heterogeneity within each progenitor population. We identified signature hallmarks of NSC, BP and NBN clusters, and predict active transcriptional nodes and networks that contribute to neural fate specification. We find that the expression of receptors, ligands and downstream pathway components is highly dynamic over time and throughout the lineage implying differential responsiveness to signals. Thus, we provide an expansive compendium of gene expression during cortical development that will be an invaluable resource for studying neural developmental processes and neurodevelopmental disorders.',
  'https://ismara.unibas.ch/NeuroStemX/',
  'Open ISMARA',
  'Mukhtar T, Taylor V. Temporal and sequential transcriptional dynamics define lineage shifts in corticogenesis. The EMBO Journal, 2022. doi: 10.15252/embj.2022111132',
  1,
  true
),
(
  'NeuroStemX · Gene expression',
  'Gene expression atlas of cortical development released with the 2022 EMBO Journal paper.',
  'The cerebral cortex contains billions of neurons, and their disorganization or misspecification leads to neurodevelopmental disorders. Understanding how the plethora of projection neuron subtypes are generated by cortical neural stem cells (NSCs) is a major challenge. Here, we focused on elucidating the transcriptional landscape of murine embryonic NSCs, basal progenitors (BPs) and newborn neurons (NBNs) throughout cortical development. We uncover dynamic shifts in transcriptional space over time, and heterogeneity within each progenitor population. We identified signature hallmarks of NSC, BP and NBN clusters, and predict active transcriptional nodes and networks that contribute to neural fate specification. We find that the expression of receptors, ligands and downstream pathway components is highly dynamic over time and throughout the lineage implying differential responsiveness to signals. Thus, we provide an expansive compendium of gene expression during cortical development that will be an invaluable resource for studying neural developmental processes and neurodevelopmental disorders.',
  'https://neurostemx.ethz.ch/#home',
  'Open gene expression atlas',
  'Mukhtar T, Taylor V. Temporal and sequential transcriptional dynamics define lineage shifts in corticogenesis. The EMBO Journal, 2022. doi: 10.15252/embj.2022111132',
  2,
  true
),
(
  'Kashmir Care Foundation',
  'Mentorship and career support for students, researchers and professionals.',
  'Kashmir Care Foundation (KCF) welcomes you to join our global network of students, researchers, and professionals. We bring together experts, mentors, and learners to advance education, research, and innovation. Supported by a diverse Advisory Group and Core Team, we aim to equip students and young professionals with the knowledge, soft skills, and technologies needed to excel in their careers and drive meaningful change. Our goal is to empower individuals from all backgrounds and locations, inspiring them to realize their full potential and become leaders in their fields.',
  'https://kashmircarefoundation.org/',
  'Visit Kashmir Care Foundation',
  '',
  3,
  true
),
(
  'GENE-India Foundation',
  'Global Education and Networking for Excellence · mentorship across India.',
  'GENE stands for Global Education and Networking for Excellence. GENE India Foundation was founded on a simple conviction: talent is everywhere, but opportunity is not. Across India''s cities, towns, and villages are students and young professionals with the drive to become tomorrow''s scientists, doctors, engineers, entrepreneurs, and leaders, but not always the mentorship, exposure, or networks to get there. GENE India exists to close that gap, connecting experienced professionals from across the globe with learners at every stage of their journey. Powered entirely by volunteers who give their time, expertise, and passion, we are building a movement rooted in mentorship, equity, and lifelong learning. Write to geneindiafoundation@gmail.com.',
  'https://www.geneindiafoundation.org',
  'Visit GENE-India Foundation',
  '',
  4,
  true
);
  end if;

  if not exists (select 1 from public.gallery_items limit 1) then
    insert into public.gallery_items (image_url, alt, caption, sort_order, published)
    values
(
  '/images/gallery/lab-team.jpg',
  'Mukhtar Lab team members together in the laboratory',
  'The team · Lab members together',
  1,
  true
),
(
  '/images/gallery/lab-duo.jpg',
  'Two Mukhtar Lab members smiling in the laboratory, one giving a thumbs up',
  'Lab mates · In the workspace',
  2,
  true
),
(
  '/images/gallery/lab-work-bsc.jpg',
  'Two researchers collaborating at a biosafety cabinet',
  'Collaboration · Biosafety cabinet',
  3,
  true
),
(
  '/images/gallery/lab-culture-work.jpg',
  'Researchers performing cell culture work at a laminar flow hood',
  'Cell culture · Sterile technique',
  4,
  true
),
(
  '/images/gallery/lab-hood-collab.jpg',
  'Two researchers collaborating at a laminar flow hood with culture dishes and pipettes',
  'At the hood · Mentorship in action',
  5,
  true
),
(
  '/images/gallery/lab-team-three.jpg',
  'Three Mukhtar Lab members posing together in the laboratory',
  'Team spirit · Together in the lab',
  6,
  true
),
(
  '/images/gallery/lab-bench-work.jpg',
  'Researcher working at a sterile laboratory workstation with culture dishes and pipettes',
  'At the bench · Culture and preparation',
  7,
  true
),
(
  '/images/gallery/lab-group-b2ac.jpg',
  'Dr. Tanzila Mukhtar presenting research at a seminar with microscopy slides on screen',
  'Seminar · Research presentation',
  8,
  true
),
(
  '/images/gallery/lab-group-outdoor.jpg',
  'Dr. Tanzila Mukhtar speaking at a podium during a scientific talk',
  'Talk · At the lectern',
  9,
  true
),
(
  '/images/gallery/lab-group-portrait.jpg',
  'Award of Appreciation plaque presented to Dr. Tanzila Mukhtar by Govt. Degree College Sopore',
  'Recognition · Award of Appreciation, GDC Sopore',
  10,
  true
),
(
  '/images/gallery/lab-seminar-side.jpg',
  'Students attending a seminar titled Parents as Pathfinders in a wood-paneled classroom',
  'Outreach · Parents as Pathfinders',
  11,
  true
),
(
  '/images/gallery/lab-seminar-front.jpg',
  'Participants seated around tables during an academic seminar',
  'Seminar · Discussion and engagement',
  12,
  true
),
(
  '/images/gallery/lab-seminar-wide.jpg',
  'Wide view of students and speakers in a classroom seminar session',
  'Outreach · Classroom session',
  13,
  true
);
  end if;
end $$;
